{"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIChallengeReason\/SMIChallengeReasonMalformed"},"metadata":{"fragments":[{"kind":"identifier","text":"SMIChallengeReasonMalformed"}],"externalID":"c:@E@SMIChallengeReason@SMIChallengeReasonMalformed","roleHeading":"Enumeration Case","navigatorTitle":[{"kind":"identifier","text":"SMIChallengeReasonMalformed"}],"title":"SMIChallengeReasonMalformed","modules":[{"name":"SMIClientCore"}],"symbolKind":"case","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIChallengeReason"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"SMIChallengeReasonMalformed","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"abstract":[{"text":"The passed in token was malformed.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/smiclientcore\/smichallengereason\/smichallengereasonmalformed"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore","url":"\/documentation\/smiclientcore","title":"SMIClientCore","role":"collection","abstract":[]},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIChallengeReason":{"fragments":[{"kind":"identifier","text":"SMIChallengeReason"}],"title":"SMIChallengeReason","kind":"symbol","type":"topic","identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIChallengeReason","abstract":[{"text":"The reason for a credential challenge. Possible values:","type":"text"}],"role":"symbol","url":"\/documentation\/smiclientcore\/smichallengereason"},"doc://com.salesforce.SMIClientCore/documentation/SMIClientCore/SMIChallengeReason/SMIChallengeReasonMalformed":{"identifier":"doc:\/\/com.salesforce.SMIClientCore\/documentation\/SMIClientCore\/SMIChallengeReason\/SMIChallengeReasonMalformed","type":"topic","abstract":[{"text":"The passed in token was malformed.","type":"text"}],"url":"\/documentation\/smiclientcore\/smichallengereason\/smichallengereasonmalformed","kind":"symbol","title":"SMIChallengeReasonMalformed","fragments":[{"kind":"identifier","text":"SMIChallengeReasonMalformed"}],"role":"symbol"}}}